# Project information
site_name: SAP NPM Explorer
site_url: https://hschaefer123.github.io/sap-npm-explorer/
site_author: Holger Schäfer
site_dir: site

# Repository
repo_name: hschaefer123/sap-npm-explorer
repo_url: https://github.com/hschaefer123/sap-npm-explorer

# Configuration
theme:
  name: material
  logo: assets/icons/udina-logo-signet.svg
  favicon: assets/icons/favicon.ico
  palette:
    primary: black
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra:
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/UNIORGGruppe
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/uniorg_gruppe/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/UNIORGGroup/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/UNIORG
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/uniorg-group/
    - icon: fontawesome/brands/xing
      link: https://www.xing.com/companies/uniorggruppe   

# Extensions
markdown_extensions:
  - attr_list
  - codehilite
  - toc:
      permalink: true

# Plugins
plugins:
  - search # necessary for search to work
  - awesome-pages # dynamically add md to nav
  - minify: # compress output
      minify_html: true